#!/bin/bash
## @author Copyright (C) 2016 Robin Schneider <ypid@riseup.net>
## @license AGPLv3 <https://www.gnu.org/licenses/agpl-3.0.html>

SANDBOX_CONF_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
. "$SANDBOX_CONF_DIR/config_common.sh"

function create_desktop_file() {
    profile="$1"
    desktop_filepath="$USER_DESKTOP_ENTRIES_DIR/userapp-sandbox-${profile}.desktop"
    (
        echo "[Desktop Entry]"
        echo "Version=1.0"
        echo "Type=Application"
        echo "Name=$profile"
        echo "Exec=$HOME/.sandboxes/bin/$profile"
        echo "Icon=${profile##*-}"
    ) > "$desktop_filepath"
}

## Delete old desktop entries (to ensure that absent profiles result in absent desktop entries).
find "$USER_DESKTOP_ENTRIES_DIR" -name 'userapp-sandbox-*.desktop' -delete

## Create desktop entries.
ls -1 "$SANDBOX_CONF_DIR" 2>/dev/zero | grep --invert-match --extended-regexp --ignore-case '^(makefile|homes|config.*)$' | while read profile
do
    create_desktop_file "$profile"
done

## Overwrite original desktop entries.
for application in $HIDE_UNSANDBOXED_APPS
do
    (
        cat "/usr/share/applications/${application}.desktop"
        echo Hidden=true
    ) > "$USER_DESKTOP_ENTRIES_DIR/${application}.desktop"
done
